### ISSUE TITLE
Getting a number of errors when trying to run `dev`

### ISSUE THREAD

**Issue by MarByteBeep** [minvws/nl-covid19-data-dashboard#3770]
When cloning, installing and running `dev`. I get the following errors in my terminal window:

```
error - Error:
Something went wrong installing the "sharp" module

The specified procedure could not be found.
\\?\C:\svn\covid_dashboard\node_modules\sharp\build\Release\sharp-win32-x64.node

Possible solutions:
- Install with the --verbose flag and look for errors: "npm install --ignore-scripts=false --verbose sharp"
- Install for the current runtime: "npm install --platform=win32 --arch=x64 sharp"
- Consult the installation documentation: https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (C:\svn\covid_dashboard\node_modules\sharp\lib\sharp.js:30:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\svn\covid_dashboard\node_modules\sharp\lib\constructor.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
event - build page: /api/topo-json/[type]
```

And my browser reports the following problem:

![image](https://user-images.githubusercontent.com/58225562/139708595-3ab00a25-8e58-4879-b96e-65b3f1f51e79.png)

Any thoughts?

**Comment by VWSCoronaDashboard1** [comment]
https://github.com/minvws/nl-covid19-data-dashboard/blob/develop/docs/developers.md
