### ISSUE TITLE
`yarn build` fails when rendering static pages

### ISSUE THREAD

**Issue by MarByteBeep** [minvws/nl-covid19-data-dashboard#3784]
* Clone clean repository
* Use the following `./packages/app/.env.local` file:

```
NEXT_PUBLIC_IS_PREVIEW_SERVER=false

PREVIEW_SERVER_NL=
PREVIEW_SERVER_EN=
DISABLE_SITEMAP=true

NEXT_PUBLIC_SANITY_PROJECT_ID=5mog5ask
SANITY_API_TOKEN=
SANITY_PREVIEW_SECRET=

# set content of version string
NEXT_PUBLIC_COMMIT_ID=n/a

NEXT_PUBLIC_SANITY_DATASET=development

# Disable compession on Windows (because of crashing Sharp module)
DISABLE_COMPRESSION=1
```

* Run the following commands

```
yarn
yarn bootstrap
cd ./packages/app
yarn download
yarn build
```

* Observe the following error:

```
[   =] info  - Generating static pages (2969/2993)
Error occurred prerendering page "/nl/landelijk/ziekenhuis-opnames". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'last_value' of null
    at IntakeHospital (C:\svn\covid\packages\app\.next\server\pages\landelijk\ziekenhuis-opnames.js:746:71)
    at d (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\svn\covid\node_modules\next\dist\server\render.js:596:45)
    at Object.ctx.renderPage (C:\svn\covid\packages\app\.next\server\pages\_document.js:51:30)
    at Function.getInitialProps (C:\svn\covid\packages\app\.next\server\chunks\331.js:603:19)
    at Function.getInitialProps (C:\svn\covid\packages\app\.next\server\pages\_document.js:55:56)

Error occurred prerendering page "/en/landelijk/ziekenhuis-opnames". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read property 'last_value' of null
    at IntakeHospital (C:\svn\covid\packages\app\.next\server\pages\landelijk\ziekenhuis-opnames.js:746:71)
    at d (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:33:498)
    at bb (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:36:16)
    at a.b.render (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:42:43)
    at a.b.read (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:41:83)
    at Object.exports.renderToString (C:\svn\covid\node_modules\react-dom\cjs\react-dom-server.node.production.min.js:52:138)
    at renderPage (C:\svn\covid\node_modules\next\dist\server\render.js:596:45)
    at Object.ctx.renderPage (C:\svn\covid\packages\app\.next\server\pages\_document.js:51:30)
    at Function.getInitialProps (C:\svn\covid\packages\app\.next\server\chunks\331.js:603:19)
    at Function.getInitialProps (C:\svn\covid\packages\app\.next\server\pages\_document.js:55:56)

info  - Generating static pages (2993/2993)

> Build error occurred
Error: Export encountered errors on following paths:
        /en/landelijk/ziekenhuis-opnames
        /nl/landelijk/ziekenhuis-opnames
    at C:\svn\covid\node_modules\next\dist\export\index.js:487:19
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Span.traceAsyncFn (C:\svn\covid\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async C:\svn\covid\node_modules\next\dist\build\index.js:833:17
    at async Span.traceAsyncFn (C:\svn\covid\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async C:\svn\covid\node_modules\next\dist\build\index.js:707:13
    at async Span.traceAsyncFn (C:\svn\covid\node_modules\next\dist\telemetry\trace\trace.js:60:20)
    at async Object.build [as default] (C:\svn\covid\node_modules\next\dist\build\index.js:77:25)
```

Also please observe that earlier the following warning is produced:

```
warn  - The Next.js plugin was not detected in your ESLint configuration. 
See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
```

**Comment by VWSCoronaDashboard7** [comment]
Which branch are you using? By default you're cloning "develop" which might not yet be compatible with the data shape as you get from "yarn download" (latest production data). Try switching to the "master" branch, that should work.

**Comment by VWSCoronaDashboard7** [comment]
I'm closing this due to inactivity. If the resolution above didn't help, feel free to reopen.
